service: cmr-stac-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  search-api:
    handler: lib/application.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: any
    environment:
      CMR_URL: 'http://localhost'
      CMR_STAC_RELATIVE_ROOT_URL: /stac
      CMR_STAC_PROTOCOL: ${opt:protocol, 'http'}
      LOG_LEVEL: info
      LOG_DISABLED: false
      STAC_VERSION: 1.0.0
      BROWSE_PATH: year/month/day

custom:
  serverless-offline:
    httpPort: 2888
    lambdaPort: 2889

plugins:
  - serverless-offline
